name: TNTRun
version: '${project.version}'
main: dev.pns.tntrun.Core
api-version: 1.8
authors: [ PnsDev ]
website: https://pns.dev
depend:
  - SlimeWorldManager
commands:
  game:
    description: The command to interact with games (mainly used for dev purposes.)
  debug:
    description: This command is purely for debugging purposes.
